### ISSUE TITLE
麻烦作者帮忙看看, 我跑不通代码

### ISSUE THREAD

**Issue by ShihuaiXu** [yzhao520/ARC#1]
thanks for your great work
我跑按照您的指导, 把nyuv2训练集和测试集分开放, 然后分别存rgb文件和depth, rgb里面存的是.png格式的原图, depth文件夹里面存的是.png格式的深度图, 然后会报错, 错误提示如下, 麻烦作者帮忙看看
/home/xsh/anaconda3/envs/arc/bin/python /home/xsh/ARC/train.py --path_to_NYUv2=/home/xsh/ARC/NYUv2 --path_to_PBRS=/home/xsh/ARC/PBRS --batch_size=4 --total_epoch_num=500 --eval_batch_size=1
3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42) 
[GCC 7.2.0]
1.5.0
project name: finetune_the_whole_system_with_depth_loss
save dir: /home/xsh/ARC/experiments/finetune_the_whole_system_with_depth_loss
Evaluating with mode: best
	Evaluation range min: 1.0 | max: 8.0
Traceback (most recent call last):
  File "/home/xsh/ARC/train.py", line 84, in <module>
    model.evaluate(mode='best')
  File "/home/xsh/ARC/training/finetune_the_whole_system_with_depth_loss.py", line 304, in evaluate
    for sample in self.dataloaders_single[set_name]:
  File "/home/xsh/anaconda3/envs/arc/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/xsh/anaconda3/envs/arc/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/xsh/anaconda3/envs/arc/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/xsh/anaconda3/envs/arc/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
SystemError: Caught SystemError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xsh/anaconda3/envs/arc/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xsh/anaconda3/envs/arc/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xsh/anaconda3/envs/arc/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xsh/ARC/dataloader/NYUv2_dataLoader.py", line 71, in __getitem__
    depth = read_array_compressed(depthname)
  File "/home/xsh/ARC/dataloader/NYUv2_dataLoader.py", line 148, in read_array_compressed
    decompressed = blosc.decompress(compressed)
  File "/home/xsh/anaconda3/envs/arc/lib/python3.6/site-packages/blosc/toplevel.py", line 508, in decompress
    return _ext.decompress(bytesobj, as_bytearray)
SystemError: <built-in function decompress> returned NULL without setting an error

**Comment by yunhan-zhao** [comment]
We save our depth files as binary files (aka .bin) to save space and for faster loading speed. Therefore, we have to decompress depth bin files first before loading them as numpy array. If your depth files are in the format of png, you should just read the image file and convert them to the format you want.

**Comment by ShihuaiXu** [comment]
感谢作者的耐心回复, 请问nyuv2的depth标签存的是绝对深度还是相对深度, 您文章模型的输出是绝对深度还是相对深度

**Comment by yunhan-zhao** [comment]
Both nyuv2 ground-truth depth maps and our model predictions are absolute depth.

**Comment by ShihuaiXu** [comment]
thank you very much, you are very helpful
我跑了您的代码, 对您这篇Domain Decluttering: Simplifying Images to Mitigate Synthetic-Real Domain Shift and Improve Depth Estimation论文有一些自己的拙见, 有不准确不对的地方还想请作者指正
首先输入一张rgb的真实图像, 然后兵分两路
   一路使用GAN网络对其进行风格迁移, 得到类似合成渲染数据的图像
   一路使用attention网络对图像中的比较hard和稀少的部分进行赋权, 得到一个mask
随后将这两路得到图像做一个element-wise的相加, inpainting网络对图像进行复原, 随后使用类似Unet的网络结构预测图像的深度, 用原始真实图像的深度ground truth去计算loss, 做梯度反传.
不知道我归纳的过程是否正确, 对于这个过程, 我有三个问题想向您请教
1.为什么要对图像进行风格迁移再修复补全, 是为了克服深度学习中的domain变化问题吗, 我看到其他基于风格迁移做单目深度估计的文章解决的问题是真实数据的标注少不准确, 而使用gan将合成渲染数据转成真实数据, 进行训练, 从而解决真实数据的标注少不准确的问题, 不知道您的这个思路想解决什么问题.
2.文章中的原图像经过GAN网络进行风格迁移随后进行图像inpanting之后进行深度预测, 这样还能用一开始真实图像的ground truth计算loss吗, 这时的ground truth会不会不准确?
3.您文章提出的单目深度估计网络是想针对真实图像的还是合成渲染图像的
我的问题比较多比较啰嗦, 希望作者有空的时候能指导我一下, 非常感谢.

**Comment by yunhan-zhao** [comment]
For the first question, the purpose of our work is to address the domain gap between real and synthetic data when training monocular depth predictors. If you check our splash figure, it clearly points out there exists a "high-level" domain gap between real and synthetic data that not yet handled by existing gan approaches. We point out these cluttered regions clearly damage the depth predictions and our ARC approach offers a solution to this problem.

For the second problem, it is true that the inpainted image is not the original image anymore. However, we expect the inpainted regions have the depth that is close enough to the original objects.  For the last question, our proposed approach is to address the problem of training with real and synthetic data together.

If you have any further questions, I would be happy to discuss them with you through emails because I would like to keep this place for code issues only.
